runtime: nodejs12

instance_class: F2

handlers:
- url: /static
  static_dir: public/static
  expiration: 30d
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  GCLOUD_TRACE_NEW_CONTEXT: 1
  APP_ENGINE_ENVIRONMENT: appengine
