#!/usr/bin/env bash
set -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
source ${DIR}/include/log-scripts.sh
if [[ $# -lt 3 ]]; then
 error "Usage: $script_name <project-id> <secret-key> <secret-value>"
 error "Example:"
 fail "       $script_name my-project-dev SOME_API_KEY amdfd0fdfkefe39fjef49f4"
fi


project_id=$1
secret_key=$2
secret_value=$3
project_option="--project=${project_id}"


printf "${secret_value}" | gcloud secrets create ${secret_key} ${project_option} --data-file=-
